---
title: "Untitled"
author: "EJR"
date: "2025-11-03"
output: html_document
editor_options: 
  chunk_output_type: console
---


black chokeberry for sgl 300 transect 7 should be burn unit 300 -2 not burn unit 300-1
# Libraries
```{r}
library(tidyverse)
library(ggridges) #for ridgeplot options
library(extrafont) #for plot font control
library(reshape2) #for site by species matrix
library(vegan) #for dissimilarity matrix
library(ggh4x) #for nested facets in plots
font_import()
```

# Species Richness and Composition
## Richness
```{r}
#import
masterdata <- read.csv("PostermasterdataSGLburns-cleaning.csv")

#clean
names(masterdata)[names(masterdata) == "Transect.."] <- "Transect" #cleaning up column name for ease of later code
masterdata <- masterdata %>%
  mutate(Species.common = recode(Species.common, "nothern dewberry" = "northern dewberry", "sassafrass" = "sassafras", "Moss morpho 3" = "moss morpho 3")) #fix typos

#summary
masterdatasummary <- masterdata %>%
  group_by(Species.common, Time.Category) %>%
  summarize(n=n_distinct(Species.common))

ggplot(masterdatasummary) + 
  theme_test() +
  geom_col(aes(x= factor(Time.Category, levels =c("0-1", "1-5", "5-10", "10+", "Never")), y=n)) +  
  xlab("Years Since Prescribed Burn") + 
  ylab("Species Richness")

```

## Species richness x location

```{r}
richness_site_summary <- masterdata %>%
  group_by(SGL, Time.Category) %>%
  summarize(n = n_distinct(Species.common))

time_labs <- c("<1", "1 - 5", "5 - 10", ">10", "No Burn")

ggplot(richness_site_summary) +
  theme_test() + 
  geom_col(aes(x = Time.Category, y = n), fill = "#223204", alpha = 0.5, color = "black", width=0.5) +
  geom_rug()+
  facet_wrap(~SGL) +
  theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        text = element_text(family = "Open Sans Semibold", size = 25)) +
  scale_x_discrete(labels = time_labs) + 
  # scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  xlab("Years Since Prescribed Burn") + 
  ylab("Richness")
```

##Ordinations, Composition 
```{r}
# omitted because creating the Latin names column isn't useful while there are observations blank for Genus/Species - will work with common names for now
# site_sp_matrix <- masterdata %>%
#   mutate(Latin = paste(Genus, Species), Point = paste(Burn.Unit, Transect)) %>%
#   select(SGL, Transect, Burn.Unit, Time.Category, Latin, Point)

#pivot to make a row for each transect and a column for each species frequency in that transect (min = 0 / absent, max = all quadrats in transect)
site_sp_matrix <- masterdata %>%
  mutate(TransectUnique = paste(Burn.Unit, Transect), Presence = "1") %>%
  dcast(TransectUnique ~ Species.common, value.var = "Presence", fun.aggregate = length, fill = 0)

#cleanup to allow vegdist() to work
rownames(site_sp_matrix) <- site_sp_matrix$TransectUnique
  
#calculate pairwise dissimilarities, Bray-Curtis
bray_matrix <- vegdist(site_sp_matrix[,2:ncol(site_sp_matrix)], method = "bray")

#calculate NMDS scores for all pairwise dissimilarities
nmds <- metaMDS(bray_matrix, trymax = 999)
ordiplot(nmds)

#export NMDS scores for ggplot  
nmds_scores <- scores(nmds, display = "sites") %>%
  as.data.frame() %>%
  rownames_to_column("TransectUnique")

#attach site and burn history information to NMDS scores list
sites <- masterdata %>%
  mutate(TransectUnique = paste(Burn.Unit, Transect)) %>%
  select(SGL, Time.Category, TransectUnique) %>%
  distinct(.keep_all = TRUE)
nmds_scores <- nmds_scores %>%
  left_join(sites, by = "TransectUnique")

#visuals
nmds_scores$SGL <- as.factor(nmds_scores$SGL)
ggplot(data = nmds_scores, aes(x = NMDS1, y = NMDS2, color = SGL, shape = Time.Category)) + geom_point(size = 5)

```


#Single site analyses
##SGL 300
```{r}

focalgenera <- read.csv("focalgenera2.csv")
time_labs <- c("<1", "1 - 5", "5 - 10", ">10", "No Burn")

#presence absence
datasummary300 <- focalgenera %>%
  filter(SGL == "300") %>%
  group_by(Genus, Time.Category, Present,) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = Present, values_from = n, values_fill = 0) %>%
  mutate(prop_present = present/(present+absent))

##text size is fixed for export at poster size
ggplot(datasummary300) +
  theme_test() + 
  geom_col(aes(x = Time.Category, y = prop_present), fill = "#223204", alpha = 0.5, color = "black", width=0.5) +
  facet_wrap(~Genus, ncol = 2) +
  theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        text = element_text(family = "Open Sans Semibold", size = 25)) +
  scale_x_discrete(labels = time_labs) + 
   scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  xlab("Years Since Prescribed Burn") + 
  ylab("Proportion of Occurrence")


#density when present

presences <- focalgenera %>%
  filter(Present == "present") 

## filter out density when present for just SGL 300
presences300 <- focalgenera %>%
  filter(Present == "present") %>%
  filter(SGL == "300")

presences_summary300 <- presences300 %>%
  group_by(Genus, Time.Category) %>%
  summarize(median = median(Daubenmeyer))

##dotplot for 300
ggplot() + 
  geom_col(data = presences_summary300, aes(x = Time.Category, y = median), width=0.5, alpha = 0.5) + 
  geom_dotplot(data = presences300, aes(x = Time.Category, y = Daubenmeyer), binaxis = "y", size = 4, alpha = 0.5, stackdir = "center") + 
  facet_wrap(~Genus, ncol = 2) + 
  theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_discrete(labels = time_labs) + 
  xlab("Time Since Prescribed Burn") + 
  ylab("Median Daubenmeyer Cover")


ggplot(presences, aes(x = Time.Category, y = Daubenmeyer)) + 
  geom_jitter(size = 5, alpha = 0.1, width = 0.2, height = 0.01) + 
  facet_wrap(~Genus, ncol=2)

presences_summary <- presences %>%
  group_by(Genus, Time.Category) %>%
  summarize(median = median(Daubenmeyer))

#dot color #223204, bar color tbd
#red is red: #7B1315

```

#Focal Genera
## Base figures for frequency, cover
```{r}
data <- read.csv("focalgenera2.csv")


#presence absence
datasummary <- data %>%
  group_by(Genus, Time.Category, Present) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = Present, values_from = n, values_fill = 0) %>%
  mutate(prop_present = present/(present+absent))

##text size is fixed for export at poster size
ggplot(datasummary) +
  theme_test() + 
  geom_col(aes(x = Time.Category, y = prop_present), fill = "#223204", alpha = 0.5, color = "black", width=0.5) +
  facet_wrap(~Genus, ncol = 2) +
  theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        text = element_text(family = "Open Sans Semibold", size = 25)) +
  scale_x_discrete(labels = time_labs) + 
   scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  xlab("Years Since Prescribed Burn") + 
  ylab("Proportion of Occurrence")


#density when present

presences <- data %>%
  filter(Present == "present")


ggplot(presences, aes(x = Time.Category, y = Daubenmeyer)) + 
  geom_jitter(size = 5, alpha = 0.1, width = 0.2, height = 0.01) + 
  facet_wrap(~Genus, ncol=2)

presences_summary <- presences %>%
  group_by(Genus, Time.Category) %>%
  summarize(median = median(Daubenmeyer))

time_labs <- c("<1", "1 - 5", "5 - 10", ">10", "No Burn")

#median and raw data option
ggplot() + 
  theme_test() +
  geom_col(data = presences_summary, aes(x = Time.Category, y = median), fill = "#7B1315", width=0.5, alpha = 0.5, color ="black") +
  geom_jitter(data = presences, aes(x = Time.Category, y = Daubenmeyer), width = 0.14, height = 0, size = 4, alpha = 0.5, pch = 21, fill = "#7B1315", color = "black") + 
  facet_wrap(~Genus, ncol = 2) +
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        text = element_text(family = "Open Sans Semibold", size = 25)) +
  scale_x_discrete(labels = time_labs) + 
  scale_y_continuous(limits = c(0, 5.2), expand = c(0,0)) +
  xlab("Years Since Prescribed Burn") + 
  ylab("Median Daubenmeyer Cover")

#dot color #223204, bar color tbd
#red is red: #7B1315


#dotplot option
ggplot() + 
  geom_col(data = presences_summary, aes(x = Time.Category, y = median), width=0.5, alpha = 0.5) + 
  geom_dotplot(data = presences, aes(x = Time.Category, y = Daubenmeyer), binaxis = "y", size = 4, alpha = 0.5, stackdir = "center") + 
  facet_wrap(~Genus, ncol = 2) + 
  theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_discrete(labels = time_labs) + 
  xlab("Time Since Prescribed Burn") + 
  ylab("Median Daubenmeyer Cover")


#ridgeline option
ggplot(presences, aes(y = Time.Category, x = Daubenmeyer)) + 
  geom_density_ridges(quantile_lines = TRUE, quantiles = 2, jittered_points = TRUE) + 
  facet_wrap(~Genus, ncol = 2) + 
  theme_test()


#binline option
ggplot(presences, aes(x = Daubenmeyer, y = Time.Category)) +
  geom_density_ridges(stat = "binline", bins = 5, scale = 2.2) +
  facet_wrap(~Genus, ncol = 2)

#fluctuation plot option
presence_tabs <- presences %>%
  group_by(Genus, Time.Category, Daubenmeyer) %>%
  summarize (N = n())

ggplot(presence_tabs, aes(x = Time.Category, y = Daubenmeyer)) + 
  geom_point(aes(size = N, alpha = N), stroke = NA)+
  scale_size_continuous(range = c(3, 15)) +
  facet_wrap(~Genus, ncol = 2) +
    theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  scale_x_discrete(labels = time_labs) + 
  xlab("Time Since Prescribed Burn") + 
  ylab("Median Daubenmeyer Cover")
             

```

## Frequency, cover separated by site

```{r}
genus_site_summary <- data %>%
  group_by(SGL, Genus, Time.Category, Present,) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = Present, values_from = n, values_fill = 0) %>%
  mutate(prop_present = present/(present+absent))


ggplot(genus_site_summary) +
  theme_test() + 
  geom_col(aes(x = Time.Category, y = prop_present), fill = "#223204", alpha = 0.5, color = "black", width=0.5) +
  geom_rug()+
  facet_nested(Genus ~ SGL) +
  theme_test() + 
  theme(strip.text = element_text(face = "italic"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        text = element_text(family = "Open Sans Semibold", size = 25)) +
  scale_x_discrete(labels = time_labs) + 
  # scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  xlab("Years Since Prescribed Burn") + 
  ylab("Proportion of Occurrence")
```


#Old Code

```{r}
#OLD
data <-read.csv("PostermasterdataSGLburns.csv")

cleandata <- data %>%
  filter(Genus %in% c("Gaylussacia", "Rubus", "Vaccinium", "Gaultheria"))

datasummary <- cleandata %>%
  group_by(Genus, Time.Category) %>%
  summarize (median = median(Daubenmeyer))

ggplot(cleandata, aes(x = Time.Category, y = Daubenmeyer)) + geom_jitter(size = 5, alpha = 0.1, width = 0.2) + facet_wrap(~Genus, ncol=2)

write.csv(cleandata, "focalgenera.csv")
```


